name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: abhigyan-709
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C

          # Notable repos
          plugin_notable: yes
          plugin_notable_from: starred
          plugin_notable_repositories: yes

          # Lines of code & traffic
          plugin_lines: yes
          plugin_traffic: yes

          # Output file
          filename: metrics.svg
